name: Build app and deploy to aliyun

on:
  push:
    branches:
      - main
jobs:
  build:
    # runs-on 指定job任务运⾏所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
          # 获取源码
          - name: Checkout
            # 使⽤action库 actions/checkout获取源码
            uses: actions/checkout@master
            # 安装Node10
          
          - name: use Node.js 12.19.0
            # 使⽤action库 actions/setup-node安装node
            uses: actions/setup-node@v1
            with:
              node-version: 12.19.0
          # 安装依赖
          - name: Yarn install
            run: npm install yarn && yarn install
            # 打包
          - name: Yarn build
            run: yarn run build:prod
            # 部署到阿⾥云
          - name: Deploy to Aliyun
            uses: easingthemes/ssh-deploy@v2.1.1
            env:
              # 私钥
              SSH_PRIVATE_KEY: ${{ secrets.COMPANY_KEY }}
              # scp参数
              ARGS: "-avzr --delete"
              # 源⽬录
              SOURCE: "dist"
              # 服务器ip：换成你的服务器IP
              REMOTE_HOST: "81.69.24.152"
              # ⽤户
              REMOTE_USER: "root"
              # ⽬标地址
              TARGET: "/root/honor-admin/client"
          # 接⼝代码打包
          - name: API build
            run: cd mock && tsc -P tsconfig.json && cp swagger.yml ./dist && cp package.json ./dist
          # 部署到阿⾥云
          - name: Deploy to Aliyun
            uses: easingthemes/ssh-deploy@v2.1.1
            env:
              # 私钥
              SSH_PRIVATE_KEY: ${{ secrets.COMPANY_KEY }}
              # 源⽬录
              SOURCE: "./mock/dist"
              # 服务器ip
              REMOTE_HOST: "81.69.24.152"
              # ⽤户
              REMOTE_USER: "root"
              # ⽬标地址
              TARGET: "/root/honor-admin/server"
